[package]
name = "overseer_voxel"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]

[dependencies]
cgmath = "0.9.1"
num-traits = "0.1.32"
glutin = "0.4.8"
gfx = "0.10.1"
gfx_core = "0.2.0"
gfx_device_gl = "0.9.0"
gfx_window_glutin = "0.10.0"