[package]
name = "overseer_voxel"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]

[dependencies.gtk]
version = "0.0.7"
features = ["v3_16"]

[dependencies]
gobject-sys = "0.3.0"
epoxy = "0.0.2"
gfx = "0.10.2"
gfx_core = "0.2.1"
gfx_device_gl = "0.9.0"
gl = "0.6.0"